version: '2.1'
services:
  sa-proxy:
    build: ./sa-proxy/
    depends_on:
      - sa-api
    ports:
      - "80:80"
  sa-api:
    build: ./sa-api/
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      AUTH_URL: 'sa-auth-ms'
      AUTH_PORT: '4000'
      AUTH_ENTRY: 'sa-auth-ms/resources/users'
    depends_on:
      - sa-auth-ms
  sa-auth-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: auth
      MYSQL_USER: sa
      MYSQL_PASSWORD: 2019ii
    ports:
      - "3306:3306"
  sa-auth-ms:
    build: ./sa-auth-ms/
    environment:
      PORT: '4000'
    depends_on:
      - sa-auth-db